name: dpp-2501
channels: 
  - defaults
#  - conda-forge  # Możesz dodać conda-forge, aby mieć szerszy dostęp do pakietów

dependencies:
  - python=3.12
  - jupyter
  - numpy
  - pandas
  - matplotlib = 3.9.2
  - seaborn = 0.13.2
  - scikit-learn
  - imbalanced-learn
  - requests
  - sqlalchemy
  #- pip  # Włączenie obsługi pip w środowisku
  #- pip:
  #  - pdpipe==0.0.53  # Instalacja pakietu pdpipe za pomocą pip
  