name: dpp-2501
channels: 
  - defaults

dependencies:
  - python=3.12
  - jupyter
  - numpy
  - pandas
  - matplotlib = 3.9.2
  - seaborn = 0.13.2
  - scikit-learn
  - imbalanced-learn
  - requests
  - sqlalchemy
  